#!/usr/bin/expect

set timeout 30
set password "iMpresora\$2016A"
set ip "157.230.138.178"
set user "root"

puts "Por favor ingresa tu OpenAI API Key:"
flush stdout
gets stdin apikey

spawn ssh $user@$ip "cd /root/active-scan-insight && docker compose down && OPENAI_API_KEY=$apikey docker compose up -d"
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "assword:" { send "$password\r" }
}
expect eof
